import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import RegisterModal from "../components/Modals/RegisterModal";
import getCurrentUser from "./actions/getCurrentUser";
import LoginModal from "../components/Modals/LoginModal";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const currentUser = await getCurrentUser();
console.log(currentUser);

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<RegisterModal />
				<LoginModal />
				{children}
				<Footer />
			</body>
		</html>
	);
}
